apiVersion: v1
kind: Namespace
metadata:
  name: developers-namespace

---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: Role
metadata:
  name: developers-role
  namespace: developers-namespace

rules:
  - apiGroups: [""]
    resources: ["pods", "services", "deployments"]
    verbs: ["get", "list", "create", "update", "delete"]
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp
data:
  key: value
