apiVersion: v1
kind: Namespace
metadata: 
  labels:
    app: developers-namespace
  name: developers-namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: developers-namespace
  name: dev-role
rules:
- apiGroups: [""]
  resources: ["pods"]  
  verbs: ["get", "update", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-rolebinding
  namespace: developers-namespace
subjects:
- kind: User
  name: devteam
  apiGroup: ""
roleRef:
  kind: Role
  name: dev-role
  apiGroup: ""